I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 38, in script
    with fadeas
  File "game/script.rpy", line 38, in <module>
    with fadeas
NameError: name 'fadeas' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 38, in script
    with fadeas
  File "D:\Program Files\renpy8.1.1\renpy-8.1.1-sdk\renpy\ast.py", line 1671, in execute
    trans = renpy.python.py_eval(self.expr)
  File "D:\Program Files\renpy8.1.1\renpy-8.1.1-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Program Files\renpy8.1.1\renpy-8.1.1-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 38, in <module>
    with fadeas
NameError: name 'fadeas' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.1.23060707
文学少年之死 1.0
Sat Aug 26 14:01:40 2023
